global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "autoscaler_backend"
    static_configs:
      - targets: ["192.168.49.2:30145"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
      
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
