apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autoscaler-ingress
  namespace: autoscalerai
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"   # allows regex-based path rewriting
spec:
  ingressClassName: nginx
  rules:
    - host: autoscaler.local
      http:
        paths:
          - path: /frontend(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
          - path: /backend(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-service
                port:
                  number: 3500
